[package]
name = "ve"
version = "0.1.1"
edition = "2021"

[lib]
name = "ve"
path = "src/lib.rs"

[[bin]]
name = "test"
path = "src/test.rs"

[dependencies]
anyhow = "1.0.75"
vibrato = "0.5.1"
zstd = "0.13.0"
